[project]
name = "robotComms"
version = "0.1"
dependencies = [
"annotated-types==0.7.0",
"black==24.10.0",
"jedi==0.19.1",
"pydantic==2.9.2",
"pydantic_core==2.23.4",
"pytest==8.3.3",
"python-dateutil==2.9.0.post0",
"typing_extensions==4.12.2",
]

[tool.ruff.lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "B"]

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["E501"]

# 3. Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

# 4. Ignore `E402` (import violations) in all `__init__.py` files, and in selected subdirectories.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]

[tool.ruff.format]
# 5. Use single quotes in `ruff format`.
quote-style = "single"

[tool.black] 
line-length = 100 
target-version = ['py39']
