name: Python checks
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -e .[dev]

      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff check src/robotComms/ --select=E9,F63,F7,F82
          # exit-zero treats all errors as warnings.
          ruff check src/robotComms/* --exit-zero

      - name: Check formatting with black
        run: |
          black src/robotComms/

          #      - name: Run unit tests
          #        run: |
          #          pytest
